#pragma once


enum ID_PROPERTY_DATA
{
	ID_PROPERTY_CLASS_EMPTY,	//	0
	ID_PROPERTY_CLASS1_NAME,	//	1
	ID_PROPERTY_CLASS1_RATIO,	//	2
	ID_PROPERTY_CLASS2_NAME,	//	
	ID_PROPERTY_CLASS2_RATIO,	//	4
	ID_PROPERTY_CLASS3_NAME,	//	
	ID_PROPERTY_CLASS3_RATIO,	//	
	ID_PROPERTY_CLASS4_NAME,	//	
	ID_PROPERTY_CLASS4_RATIO,	//	8
	ID_PROPERTY_CLASS5_NAME,	//	
	ID_PROPERTY_CLASS5_RATIO,	//	
	ID_PROPERTY_GAIN,			//	11

	ID_PROPERTY_INDEX_TRUECOLOR, // 11

	ID_PROPERTY_COUNT		//	12
};
